project:
  type: book
  
execute: 
  freeze: auto
  echo: fenced

book:
  title: "強化学習 輪読会"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd

highlight-style: pygments

format:
  html:
    html-math-method:
      method: mathjax
    number-sections: false
    code-copy: true
    theme: cosmo
    css: css/styles.css
  pdf:
    documentclass: scrreprt

editor: visual

