project:
  type: book
  
execute: 
  freeze: auto

book:
  title: "強化学習第2版 輪読会"
  date: "2022/11/29"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

