---
jupyter: python3
---

参加者: ろく、峻平

## 輪読会にあたって

第１章以降、とくに第Ⅱ部（第９章〜）からはそれぞれが独立した内容が多い。

最初にすべての難易度を把握するのは難しいので、毎週次回の担当範囲を決めることとする。

本の内容に沿って解説していき、わからないところがあれば聞き手はよこやりを入れて質問をしてよい。

担当者はすべての質問に答えられるように準備する。

## 当書で使われる記号

```{python}
1 + 1
```

## 今後の進め方

二人で共通の文書を編集する形式に賛成であれば、次回までにこの文書をサーバーにアップロードし、峻平への導入方法を考えておく。

| 日時  | ろく         | 峻平         |
|:-----:|--------------|--------------|
| 11/30 | 序章         |              |
| 12/5  | 第一章       |              |
| 12/12 | 第二章前半？ | 第二章後半？ |
| 12/19 |              |              |
| 12/26 |              |              |
|  1/2  |              |              |

そうでなければ、例えば一人はbook形式、もう一人はスライドを用いて発表する。

## 文書の編集方法

1.  git環境を整える。（wslがおすすめ）
2.  [rstudio](https://posit.co/download/rstudio-desktop/)と[quarto](https://quarto.org/docs/get-started/)をインストール
3.  <https://github.com/Roku-3/rindoku_RL>にアクセスし、mainブランチでリポジトリをクローンする。rstudioで開く。

### 編集内容を適応する

gitの基本コマンドは以下の通り。

``` bash
git pull origin HEAD            # githubからローカルに差分をもってくる

git add .                       # 全てのファイルをコミット対象にする

git commit -m "edit chapter 2"  # 編集内容を表すコメント付きでコミットする。
                                # -mはコミットメッセージを一行にするという意味
                                
git push origin HEAD            # githubに情報を送る
```

2人が同じ場所を変更していた場合、コンフリクトが発生する。その時は必ず解消してからpushを行う。

`git branch`と入力したときに`main`になっていることを確認してからpushすること。\
pushが正常に行われると自動でデプロイ（サイトが公開）される。

### 今後の運用

一人が文書を変更して適応した後、細かいミスなどで再編集するのは手間。また間違ってファイルを削除してしまった時の危険性も高い。

そのため、後々はプルリクエストを出してもう一人が確認する形式にしようと思う。

プルリクエストは手軽に人の編集を確認・訂正できるgithubの機能である。
